backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Index Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Intro, name: intro, widget: object, fields: [{label: Title, name: title, widget: string},{label: Heading, name: heading, widget: string},{label: Subheading, name: subheading, widget: string},{label: Image, name: image, widget: image}]}
          - {label: Services, name: services, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Services, name: services, widget: list, fields: [{label: Image, name: image, widget: image},{label: Heading, name: heading, widget: string},{label: Description, name: description, widget: text}]}]}
          - {label: Portfolio, name: portfolio, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Jobs, name: jobs, widget: list, fields: [{label: Images, name: images, widget: list, fields: [{label: Image, name: image, widget: image}]},{label: Location, name: location, widget: string}, {label: Services, name: services, widget: list}]}]}
          - {label: About, name: about, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Team, name: team, widget: list, fields: [{label: Image, name: image, widget: image},{label: Name, name: name, widget: string}, {label: Info, name: info, widget: list}]}]}
          - {label: Contact, name: contact, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Background, name: background, widget: image}, {label: Links, name: links, widget: list, fields: [{label: Type, name: type, widget: string}, {label: Label, name: label, widget: string}, {label: Address, name: address, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}